name: Sven337
description: Reverse engineering the world, one device at a time
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
baseurl: /~sven337
url: https://perso.aquilenet.fr/
encoding: UTF-8
slideshow:
    width: 300
    height: 300
plugins:
  - jekyll-redirect-from
