name: Sven337
description: Computers, electronics, politics
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
baseurl: /~sven337
encoding: UTF-8
url: http://perso.aquilenet.fr/~sven337
slideshow:
    width: 300
    height: 300
